# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'page3.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form31(object):
    def setupUi(self, Form31):
        Form31.setObjectName("Form31")
        Form31.resize(801, 618)
        self.label = QtWidgets.QLabel(Form31)
        self.label.setGeometry(QtCore.QRect(0, 0, 801,618))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("44.png"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Form31)
        self.label_2.setGeometry(QtCore.QRect(180, 5, 501, 60))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(35)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color: rgb(13,106,121); background-color: rgb(131,238,255);")
        self.label_2.setObjectName("label_2")

        self.pushButton = QtWidgets.QPushButton(Form31)
        self.pushButton.setGeometry(QtCore.QRect(560, 450, 171, 51))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("border-radius:20px;\n"
                                       "background-color: rgb(140,120,120);")
        self.pushButton.setObjectName("pushButton")
        self.pushButton.clicked.connect(self.entry)

        self.pushButton3 = QtWidgets.QPushButton(Form31)
        self.pushButton3.setGeometry(QtCore.QRect(560, 530, 171, 51))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton3.setFont(font)
        self.pushButton3.setStyleSheet("border-radius:20px;\n"
                                      "background-color: rgb(140,120,120);")
        self.pushButton3.setObjectName("pushButton")
        self.pushButton3.clicked.connect(self.clear)



        self.retranslateUi(Form31)
        QtCore.QMetaObject.connectSlotsByName(Form31)

    def __init__(self):
        self.cv2_window_name = "Video"
        self.exit_requested = False

    def retranslateUi(self, Form31):
        _translate = QtCore.QCoreApplication.translate
        Form31.setWindowTitle(_translate("Form3", "Form"))
        self.label_2.setText(_translate("Form3", "FACE RECOGNITION"))
        self.pushButton.setText(_translate("Form3", "DETECT FACE"))
        # self.pushButton2.setText(_translate("Form3", "OUT"))
        self.pushButton3.setText(_translate("Form3", "EXIT"))

    def clear(self):
        import cv2
        Form31.close()
        cv2.destroyWindow(self.cv2_window_name)
        QtWidgets.QApplication.quit()
        self.exit_requested = True
    def entry(self):
        print("welcome")
        import cv2
        import mediapipe as mp
        import os
        import json
        import face_recognition
        import csv
        import time

        # Create a directory to save the landmarks
        output_dir = "landmarks_output"
        os.makedirs(output_dir, exist_ok=True)

        # Create a directory for known faces
        known_faces_folder = "faces"
        os.makedirs(known_faces_folder, exist_ok=True)

        # Initialize Face Mesh
        mp_face_mesh = mp.solutions.face_mesh
        face_mesh = mp_face_mesh.FaceMesh()



        # Function to load known face encodings
        def load_known_encodings(known_faces_folder):
            known_face_encodings = []
            known_face_names = []

            for filename in os.listdir(known_faces_folder):
                if filename.endswith((".jpg", ".png", ".jpeg")):
                    name = os.path.splitext(filename)[0]
                    image_path = os.path.join(known_faces_folder, filename)
                    face_image = face_recognition.load_image_file(image_path)
                    face_encoding = face_recognition.face_encodings(face_image)[0]
                    known_face_encodings.append(face_encoding)
                    known_face_names.append(name)

            return known_face_encodings, known_face_names

        # Load known face encodings and names
        known_face_encodings, known_face_names = load_known_encodings(known_faces_folder)

        # Initialize Video Capture
        video_capture = cv2.VideoCapture(0)  # Use the default camera (change to a file or camera index if needed)

        while True:
            # Capture frame-by-frame
            ret, frame = video_capture.read()
            if not ret:
                break
            if self.exit_requested:  # Check the exit flag
                break

                # Convert the frame to RGB for face mesh and face recognition
            rgb_frame = cv2.cvtColor(frame, cv2.COLOR_BGR2RGB)

            # Perform face mesh detection
            result = face_mesh.process(rgb_frame)

            # Get image dimensions
            height, width, _ = frame.shape

            # Create a list to store landmarks
            landmarks_list = []

            if result.multi_face_landmarks:
                # Iterate through detected faces
                for facial_landmarks in result.multi_face_landmarks:
                    for i in range(0, 468):
                        pt1 = facial_landmarks.landmark[i]
                        x = int(pt1.x * width)
                        y = int(pt1.y * height)
                        landmarks_list.append((x, y))

                # Save the landmarks as a JSON file
                output_filename = "landmarks.json"
                output_path = os.path.join(output_dir, output_filename)

                with open(output_path, "w") as json_file:
                    json.dump(landmarks_list, json_file)

            # Real-time face recognition
            face_locations = face_recognition.face_locations(rgb_frame)
            face_encodings = face_recognition.face_encodings(rgb_frame, face_locations)

            for (top, right, bottom, left), face_encoding in zip(face_locations, face_encodings):
                # Try to match the face encoding with known faces
                matches = face_recognition.compare_faces(known_face_encodings, face_encoding)

                name = "Unknown"  # Default name if no match found
                confidence = None

                for i, is_match in enumerate(matches):
                    if is_match:
                        confidence = 100 - face_recognition.face_distance([known_face_encodings[i]], face_encoding)[0]
                        if confidence > 99.5:
                            name = known_face_names[i]
                            print(name)
                            print(".................................")
                            print("Face identified")
                            time.sleep(3)
                            print(".................................")
                            print("Authentication is successful")
                            time.sleep(3)
                            print(".................................")
                            print("Proceed with your transaction")

                            time.sleep(3)

                            video_capture.release()
                            cv2.destroyAllWindows()

                            return

                # Draw a rectangle around the face
                cv2.rectangle(frame, (left, top), (right, bottom), (255,0, 0), 2)

                # Display the name (without confidence) on top of the rectangle
                font = cv2.FONT_HERSHEY_DUPLEX
                cv2.putText(frame, name, (left + 6, top - 6), font, 2, (255,0, 0), 2)

            # Display the resulting frame
            cv2.imshow('Video', frame)

            # Break the loop if 'q' is pressed
            if cv2.waitKey(1) & 0xFF == ord('q'):
                break

        # Release the video capture object and close all windows
        video_capture.release()
        cv2.destroyAllWindows()





if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form31 = QtWidgets.QWidget()
    ui = Ui_Form31()
    ui.setupUi(Form31)
    Form31.show()
    sys.exit(app.exec_())
