# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'page2.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from otp import Ui_Form4


class Ui_Form22(object):
    def setupUi(self, Form22):
        Form22.setObjectName("Form22")
        Form22.resize(745, 591)
        self.label = QtWidgets.QLabel(Form22)
        self.label.setGeometry(QtCore.QRect(0, 0, 751, 601))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("22.webp"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Form22)
        self.label_2.setGeometry(QtCore.QRect(300, 10, 100, 51))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(35)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color: rgb(13,106,121); background-color: rgb(131,238,255)")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Form22)
        self.label_3.setGeometry(QtCore.QRect(50, 300, 361, 51))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(28)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("color: rgb(255,255,255);")
        self.label_3.setObjectName("label_3")


        self.lineEdit_2 = QtWidgets.QLineEdit(Form22)
        self.lineEdit_2.setGeometry(QtCore.QRect(400, 300, 251, 41))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        self.lineEdit_2.setFont(font)
        self.lineEdit_2.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.pushButton = QtWidgets.QPushButton(Form22)
        self.pushButton.setGeometry(QtCore.QRect(270, 500, 171, 51))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("border-radius:20px;\n"
"background-color: rgb(140,120,120);")
        self.pushButton.setObjectName("pushButton")
        self.pushButton.clicked.connect(self.next_page)


        self.lineEdit_21 = QtWidgets.QLineEdit(Form22)
        self.lineEdit_21.setGeometry(QtCore.QRect(60, 400, 381, 51))
        self.lineEdit_21.setStyleSheet("background-color: rgba(0, 0, 0,0);\n"
                                      "border:none;\n"
                                      "border-bottom:2px solid rgba(255,255,255,255);\n"
                                      "color: rgb(255,255, 255);\n"
                                      "paddin-bottom:7px;\n"
                                      "font: 24pt \"MS Shell Dlg 2\";\n"
                                      "")
        self.lineEdit_21.setObjectName("lineEdit_21")

        self.retranslateUi(Form22)
        QtCore.QMetaObject.connectSlotsByName(Form22)

    def retranslateUi(self, Form22):
        _translate = QtCore.QCoreApplication.translate
        Form22.setWindowTitle(_translate("Form2", "Form"))
        self.label_2.setText(_translate("Form2", "PIN "))
        self.label_3.setText(_translate("Form2", "ENTER ATM PIN:"))

        self.pushButton.setText(_translate("Form2", "VERIFY"))


    def next_page(self):

        n2 = self.lineEdit_2.text()

        if n2 == '5678':
            print("correct PIN number")
            self.lineEdit_21.setText("correct PIN number")
            print("PIN authenticated successfully")
            self.Form4 = QtWidgets.QMainWindow()
            self.ui = Ui_Form4()
            self.ui.setupUi(self.Form4)
            self.Form4.show()
        else:
            print("wrong PIN number")
            self.lineEdit_21.setText("wrong PIN number")

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form22 = QtWidgets.QWidget()
    ui = Ui_Form22()
    ui.setupUi(Form22)
    Form22.show()
    sys.exit(app.exec_())
